# Generated by Django 5.0.7 on 2024-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('P', 'Primary'), ('SE', 'Secondary'), ('S', 'Success'), ('DA', 'Danger'), ('W', 'Warning'), ('I', 'Info'), ('L', 'light'), ('D', 'dark')], max_length=2),
        ),
    ]
